<?php 
require_once("./config.php");
require_once("./classes/DBConnection.php");

class Master extends DBConnection{
    /**
     * Save New Subsriber Information
     */
    function save_subscriber(){
        extract($_POST);
        if(filter_var($email, FILTER_VALIDATE_EMAIL)){
            $check_email = $this->conn->query("SELECT id FROM `subscribers` where `email` = '{$email}'")->num_rows;
            if($check_email <= 0){
                $sql = "INSERT INTO `subscribers` (`fullname`, `email`) VALUES ('{$fullname}', '{$email}')";
                try{
                    $insert = $this->conn->query($sql);
                    $resp['status'] = 'success';
                    $id = $this->conn->insert_id;
                }catch(Exception $e){
                    $resp['status'] = 'failed';
                    $resp['msg'] = $e->getMessage();
                }
                if($resp['status'] == 'success'){
                    $send_verification = $this->send_verification($id, $email, $fullname);
                    if($send_verification['status'] ='success'){
                        $resp['msg'] = "We have sent a verfication link to your mail. Click the link on mail to verify and start receiving updates from us. Thank you!";
                    }else{
                        $resp['status'] = 'warning';
                        $resp['msg'] = 'We are having trouble of sending you a verification link. Please try again later.';
                        $resp['error'] = $send_verification['error'];
                        $this->conn->query("DELETE FROM `subscribers` where `id` = '{$id}'");
                    }
                }
            }else{
                $resp['status'] = 'warning';
                $resp['msg'] = 'Given Email is already subscribed on this site.';
            }
        }else{
            $resp['status'] = 'failed';
            $resp['msg'] = 'Invalid email.';
        }

        return json_encode($resp);
    }
    /**
     * Update Subscriber as Verified
     */
    function verify_subscriber($id = ''){
        if(!empty($id)){
            $update = $this->conn->query("UPDATE `subscribers` set `is_verified` = 1 where id = '{$id}'");
            if($update){
                $get = $this->conn->query("SELECT * FROM `subscribers` where `id` = '{$id}'")->fetch_assoc();
                $send_sample = $this->sample_newsletter($get['email'], $get['fullname']);
                if($send_sample['status'] == 'success'){
                    return ['status'=>'success'];
                }else{
                 return ['status'=>'failed', 'error' => $send_sample['error']];
                }
            }else{
                return ['status'=>'failed', 'error' => $this->conn->error];
            }
        }
        return ['status'=>'failed', 'error' => "Subscriber's ID is required"];
    }
    /**
     * Send Subscription Email Verification
     */
    function send_verification($id, $email, $fullname){
        $to = $email;
        $subject = "Site Newsletter Subscription - Verification";
        $from = "webmaster@mail.com";
        $fromName = "Sample Site";
        ob_start();
        ?>
        <html>
            <head>
                <title>Sample Site - Newsletter Subscription Verification</title>
            </head>
            <body>
                <div align="center">
                    <img src="https://www.linkpicture.com/q/sample-logo.jpg" alt="Sample Site Logo">
                </div>
                <h1 align="center"><strong>Thank You for Subscribing to Sample Site!</strong></h1>
                <br>
                <br>
                <p>Greetings to you <strong>Mr/Ms/Mrs. <?= $fullname ?></strong>! This email contains a link for verifying your subscription to our site. Kindly click the link below to start receiving updates from us. Thank you!</p>
                <p>Verfication Link: <a href="<?= siteURL ?>?page=mail_verified&id=<?= $id ?>" target="_blank"><?= siteURL ?>?page=mail_verified&id=<?= $id ?></a></p>
                <br>
                <br>
                <p><em>This is only an autogenerated email. Please do not reply.</em></p>
            </body>
        </html>
        <?php
        $messageContent =ob_get_clean();
        $headers = "MIME-Version: 1.0" . "\r\n"; 
        $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n"; 
        $headers .= 'From: '.$fromName.'<'.$from.'>' . "\r\n"; 
        $headers .= "Reply-To:noreply@gmail.com\r\n"; 

        try{
            mail($to, $subject, $messageContent, $headers);
        }catch(Exception $e){
            return ['status' => 'failed', 'error'=>$e->getMessage()];
        }
        return ['status' => 'success'];
    }
    /**
     * Send Sample News Letter
     */
    function sample_newsletter($email, $fullname){
        $to = $email;
        $subject = "Sample Newsletter";
        $from = "webmaster@mail.com";
        $fromName = "Sample Site";
        ob_start();
        ?>
        <html>
            <head>
                <title>Sample Site - Sample Newsletter</title>
            </head>
            <body>
                <div align="center">
                    <img src="https://www.linkpicture.com/q/sample-logo.jpg" alt="Sample Site Logo">
                </div>
                <h1 align="center"><strong>Sample Site</strong></h1>
                <br>
                <br>
                <p>Greetings to you <strong>Mr/Ms/Mrs. <?= $fullname ?></strong>,</p>
                <br>
                <p>This is only a sample newsletter from our site. Feel free to explore more on our site <a href="<?= siteURL ?>" target="_blank">Sample Site</a> to know more about us. Thank you!</p>
                <br>
                <p>Regards,</p>
                <p>Sample Site Management</p>
                <br>
                <br>
                <p><em>This is only an autogenerated email. Please do not reply.</em></p>
            </body>
        </html>
        <?php
        $messageContent =ob_get_clean();
        $headers = "MIME-Version: 1.0" . "\r\n"; 
        $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n"; 
        $headers .= 'From: '.$fromName.'<'.$from.'>' . "\r\n"; 
        $headers .= "Reply-To:noreply@gmail.com\r\n"; 

        try{
            mail($to, $subject, $messageContent, $headers);
        }catch(Exception $e){
            return ['status' => 'failed', 'error'=>$e->getMessage()];
        }
        return ['status' => 'success'];
    }
}